/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Jesus
 */
public class Menu extends javax.swing.JFrame {
FondoPanel fondo= new FondoPanel();   

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setContentPane(fondo);
        initComponents();
        setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Menú");
       
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmenu = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        btnnivel_1 = new javax.swing.JButton();
        btnnivel_2 = new javax.swing.JButton();
        btnnivel_3 = new javax.swing.JButton();
        btnnivel_4 = new javax.swing.JButton();
        btnnivel_5 = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_acerca = new javax.swing.JButton();
        btn_creditos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menuti.png"))); // NOI18N

        btnnivel_1.setBackground(new java.awt.Color(51, 51, 255));
        btnnivel_1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnnivel_1.setForeground(new java.awt.Color(255, 255, 255));
        btnnivel_1.setText("NIVEL 1");

        btnnivel_2.setBackground(new java.awt.Color(51, 51, 255));
        btnnivel_2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnnivel_2.setForeground(new java.awt.Color(255, 255, 255));
        btnnivel_2.setText("NIVEL 2");

        btnnivel_3.setBackground(new java.awt.Color(51, 51, 255));
        btnnivel_3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnnivel_3.setForeground(new java.awt.Color(255, 255, 255));
        btnnivel_3.setText("NIVEL 3");
        btnnivel_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnivel_3ActionPerformed(evt);
            }
        });

        btnnivel_4.setBackground(new java.awt.Color(51, 51, 255));
        btnnivel_4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnnivel_4.setForeground(new java.awt.Color(255, 255, 255));
        btnnivel_4.setText("NIVEL 4");
        btnnivel_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnivel_4ActionPerformed(evt);
            }
        });

        btnnivel_5.setBackground(new java.awt.Color(51, 51, 255));
        btnnivel_5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnnivel_5.setForeground(new java.awt.Color(255, 255, 255));
        btnnivel_5.setText("NIVEL 5");
        btnnivel_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnivel_5ActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(51, 51, 255));
        btn_salir.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_acerca.setBackground(new java.awt.Color(51, 51, 255));
        btn_acerca.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_acerca.setForeground(new java.awt.Color(255, 255, 255));
        btn_acerca.setText("ACERCA DEL \n VIDEOJUEGO");
        btn_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acercaActionPerformed(evt);
            }
        });

        btn_creditos.setBackground(new java.awt.Color(51, 51, 255));
        btn_creditos.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btn_creditos.setForeground(new java.awt.Color(255, 255, 255));
        btn_creditos.setText("CRÉDITOS");
        btn_creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creditosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmenuLayout.createSequentialGroup()
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelmenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnnivel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnivel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnivel_3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnivel_4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnivel_5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(panelmenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_acerca, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addComponent(btn_creditos)
                .addGap(50, 50, 50))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnivel_1)
                .addGap(18, 18, 18)
                .addComponent(btnnivel_2)
                .addGap(18, 18, 18)
                .addComponent(btnnivel_3)
                .addGap(16, 16, 16)
                .addComponent(btnnivel_4)
                .addGap(18, 18, 18)
                .addComponent(btnnivel_5)
                .addGap(18, 18, 18)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_acerca)
                    .addComponent(btn_salir)
                    .addComponent(btn_creditos))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnivel_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnivel_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnivel_3ActionPerformed

    private void btnnivel_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnivel_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnivel_4ActionPerformed

    private void btnnivel_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnivel_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnivel_5ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acercaActionPerformed

    private void btn_creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_creditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_creditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_acerca;
    public javax.swing.JButton btn_creditos;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btnnivel_1;
    public javax.swing.JButton btnnivel_2;
    public javax.swing.JButton btnnivel_3;
    public javax.swing.JButton btnnivel_4;
    public javax.swing.JButton btnnivel_5;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel panelmenu;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen=new ImageIcon(getClass().getResource("/Imagenes/planet.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

}
