/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Jesus
 */
public class Nivel1v9 extends javax.swing.JFrame {
FondoPanel fondo= new FondoPanel();   
    /**
     * Creates new form Nivel1ini
     */
    public Nivel1v9() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Nivel 1: Números Reales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupA = new javax.swing.ButtonGroup();
        btnGroupB = new javax.swing.ButtonGroup();
        jPanel1 = new FondoPanel();
        btn1_n1v9 = new javax.swing.JButton();
        jtxt_n1v9 = new javax.swing.JTextField();
        jtxt2_n1v9 = new javax.swing.JTextField();
        rbtn_n1v9 = new javax.swing.JRadioButton();
        rbtn2_n1v9 = new javax.swing.JRadioButton();
        rbtn3_n1v9 = new javax.swing.JRadioButton();
        rbtn4_n1v9 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1_n1v9.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btn1_n1v9.setText("FINALIZAR EJERCICIO");
        jPanel1.add(btn1_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        jtxt_n1v9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_n1v9ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 140, 30));

        jtxt2_n1v9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt2_n1v9ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt2_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 140, 30));
        jPanel1.add(rbtn_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));
        jPanel1.add(rbtn2_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));
        jPanel1.add(rbtn3_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));
        jPanel1.add(rbtn4_n1v9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nivel1/ej3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_n1v9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_n1v9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_n1v9ActionPerformed

    private void jtxt2_n1v9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt2_n1v9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt2_n1v9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel1v9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel1v9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel1v9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel1v9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel1v9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn1_n1v9;
    public javax.swing.ButtonGroup btnGroupA;
    public javax.swing.ButtonGroup btnGroupB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jtxt2_n1v9;
    public javax.swing.JTextField jtxt_n1v9;
    public javax.swing.JRadioButton rbtn2_n1v9;
    public javax.swing.JRadioButton rbtn3_n1v9;
    public javax.swing.JRadioButton rbtn4_n1v9;
    public javax.swing.JRadioButton rbtn_n1v9;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen=new ImageIcon(getClass().getResource("/Nivel1/nivel1fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
