/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author Leonardo Coronado
 */
public class Nivel4v15 extends javax.swing.JFrame {
FondoPanel fondo= new FondoPanel();
    /**
     * Creates new form Nivel4v15
     */
    public Nivel4v15() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Nivel 4: Derivadas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        jtxt1_n4v15 = new javax.swing.JTextField();
        jtxt3_n4v15 = new javax.swing.JTextField();
        jtxt4_n4v15 = new javax.swing.JTextField();
        jtxt5_n4v15 = new javax.swing.JTextField();
        jtxt2_n4v15 = new javax.swing.JTextField();
        jtxt7_n4v15 = new javax.swing.JTextField();
        jtxt8_n4v15 = new javax.swing.JTextField();
        b1_n4v15 = new javax.swing.JButton();
        jtxt9_n4v15 = new javax.swing.JTextField();
        jtxt10_n4v15 = new javax.swing.JTextField();
        jtxt6_n4v15 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxt1_n4v15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt1_n4v15ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt1_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 60, 30));
        jPanel1.add(jtxt3_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 60, 30));
        jPanel1.add(jtxt4_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 60, 30));
        jPanel1.add(jtxt5_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 60, 30));
        jPanel1.add(jtxt2_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 60, 30));
        jPanel1.add(jtxt7_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 80, 30));
        jPanel1.add(jtxt8_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 80, 30));

        b1_n4v15.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        b1_n4v15.setText("FINALIZAR PRUEBA");
        jPanel1.add(b1_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 250, 50));
        jPanel1.add(jtxt9_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 80, 30));
        jPanel1.add(jtxt10_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 80, 30));
        jPanel1.add(jtxt6_n4v15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nivel4/Nivel4v15.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt1_n4v15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt1_n4v15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt1_n4v15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel4v15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel4v15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel4v15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel4v15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel4v15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b1_n4v15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jtxt10_n4v15;
    public javax.swing.JTextField jtxt1_n4v15;
    public javax.swing.JTextField jtxt2_n4v15;
    public javax.swing.JTextField jtxt3_n4v15;
    public javax.swing.JTextField jtxt4_n4v15;
    public javax.swing.JTextField jtxt5_n4v15;
    public javax.swing.JTextField jtxt6_n4v15;
    public javax.swing.JTextField jtxt7_n4v15;
    public javax.swing.JTextField jtxt8_n4v15;
    public javax.swing.JTextField jtxt9_n4v15;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g)
        {
            imagen=new ImageIcon(getClass().getResource("/Nivel1/nivel1fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
